# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [3]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [23]:
# Creating arrays

a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

#Think of a numpy array as a multidimensional matrix
#b = Returns a 2 by 3 matrix of all ones
#c = Returns 2 matricies that will be of dimensions 3 by 4.  
#c = The values will be randomly selected between 1-9
#these functions follow a discrete uniform distribution 
#(every event has an equal likelihood of occuring)

In [5]:
print a
print b
print c
print d

[ 0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[[7 9 4 8]
  [2 3 6 5]
  [2 7 6 7]]

 [[1 8 6 9]
  [4 8 4 8]
  [6 9 6 2]]]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [26]:
e = np.random.randint(1,10,2)
print e
#The 2 tells you how many times you are picking from the distribution


f = np.random.randint(4)
print f
#This will only ever return one randomly generated number n-1, so 4-1

[9 8]
2


What are these functions?

    arange?

In [ ]:
# Note the way each array is printed:
a,b,c,d

In [ ]:
## Arithmetic in arrays is element wise

In [6]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [7]:
c = a-b
c

array([20, 29, 38, 47])

In [8]:
b**2

array([0, 1, 4, 9])

In [9]:
map( lambda x: x**2, [0,1,2,3])

[0, 1, 4, 9]

## Indexing, Slicing and Iterating

In [11]:
# one-dimensional arrays work like lists:
# if you do not specify the min and the max... the function will
# assume 0 for the min and then the value (e.g.10) as the max
# always n-1

a = np.arange(10)**2
print a

[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
someList = [1,2,3]

#how to get just the first two numbers?
someList[0:2]

[1, 2]

In [15]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [17]:
b = np.random.randint(1,100,(4,4))

In [18]:
b

array([[ 4, 72, 24, 17],
       [47,  5, 76, 33],
       [89, 33, 80, 86],
       [81, 80, 81, 35]])

In [ ]:
# Guess the output
print(b[2,3])
print(b[0,0])


#How you can get a scalar constant out of a matrices... rows then columns
#print(b[2,3]) row 2, column 3 where you start you column count from 0

In [ ]:
b[0:3,1],b[:,1]

In [ ]:
b[1:3,:]

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [82]:
dates = pd.date_range('20140101',periods=6)
dates

# 6 steps and the frequencey default is by Day
#very quick way to generate dates for your dataset
#object is a DatetimeIndex

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [83]:
dates = pd.date_range('20140101',periods=6, freq="365D")
print dates

DatetimeIndex(['2014-01-01', '2015-01-01', '2016-01-01', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='365D')


In [84]:
date1 = dates[0]
#the zero will return the first timestamp
#a DatetimeIndex returns to you a collection of timestamps
#timestamps are helpful because you can query on time
#in your dataframe if you have a string date...convert to date

In [85]:
print date1.day
print date1.month
print date1.year

1
1
2014


In [86]:
import time
time.localtime()

time.struct_time(tm_year=2016, tm_mon=11, tm_mday=14, tm_hour=21, tm_min=0, tm_sec=13, tm_wday=0, tm_yday=319, tm_isdst=0)

In [87]:
np.random.randn(6,4)

#.randn method returns randomly generated numbers from a normal dist
#.randint method returns randomly generated numbers from a discrete uniform dist

array([[-1.155816  , -0.27894284, -1.00237716,  0.68183095],
       [-0.50155832, -0.51593466, -0.05260828, -1.02893989],
       [-1.25892731,  0.85967577, -0.29178526,  0.6198711 ],
       [-0.4996562 ,  0.47003214,  0.12550091,  0.48036844],
       [ 1.31827133,  0.94428953, -0.51140569,  1.01747634],
       [ 1.81904542, -0.47546176, -0.64655689, -1.44510183]])

In [88]:
list('AB')

#if you ever want to split a string by a character you ust this

['A', 'B']

In [89]:
df = pd.DataFrame(np.random.randn(6,5),index=dates,columns=list('ABCDE'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

#dates were made into the index column
#a TimeUUID = is a time universal unique identifier

Index([u'A', u'B', u'C', u'D', u'E'], dtype='object')

In [90]:
df.head()
#this is default 5 rows

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521  0.747274
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.457958

In [91]:
# Index, columns, underlying numpy data
df.T

#.T will transpose...make your rows your columns

2014-01-01  2015-01-01  2016-01-01  2016-12-31  2017-12-31  2018-12-31
A   -0.715416    0.026003   -0.020582   -0.538891    0.845594   -0.182122
B    0.859711   -0.089616   -0.587065   -0.677628   -0.616776   -0.894725
C   -0.176055   -0.025000   -1.613610   -1.321461   -0.164049    1.023244
D    0.070512    0.817799   -0.648030   -1.046521   -0.181428   -2.232250
E   -0.781229    0.650946   -0.824425    0.747274   -0.457958    1.313546

In [92]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2
#here we are hard-coding the dataframe
#use parse_dates to convert string dates to a date
#Column names are defined by the keys
#1. is a float because it's a decimal
#[a]*4 will return [a,a,a,a]


A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [93]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [51]:
df.head()

A         B         C         D         E
2014-01-01  1.123726  0.148691  0.191924  0.636486 -0.835854
2015-01-01  0.873381  0.081151  0.569249 -0.799956 -1.093809
2016-01-01 -0.525486  1.180151  1.439420  1.486988  0.192667
2016-12-31  0.770334  0.333293  1.600785  1.055417 -1.065898
2017-12-31 -1.169524 -1.355800  0.337845 -0.568655 -1.688358

In [52]:
df.tail()

A         B         C         D         E
2015-01-01  0.873381  0.081151  0.569249 -0.799956 -1.093809
2016-01-01 -0.525486  1.180151  1.439420  1.486988  0.192667
2016-12-31  0.770334  0.333293  1.600785  1.055417 -1.065898
2017-12-31 -1.169524 -1.355800  0.337845 -0.568655 -1.688358
2018-12-31  0.163111 -1.186679 -0.479321 -1.089277 -0.370649

In [53]:
df.index

DatetimeIndex(['2014-01-01', '2015-01-01', '2016-01-01', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='365D')

In [54]:
df.describe()

A         B         C         D         E
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   0.205924 -0.133199  0.609984  0.120167 -0.810317
std    0.898339  0.966694  0.788255  1.076414  0.650628
min   -1.169524 -1.355800 -0.479321 -1.089277 -1.688358
25%   -0.353337 -0.869722  0.228404 -0.742130 -1.086831
50%    0.466723  0.114921  0.453547  0.033916 -0.950876
75%    0.847619  0.287142  1.221877  0.950684 -0.486950
max    1.123726  1.180151  1.600785  1.486988  0.192667

In [95]:
df.sort_values(by='B')
#df.sort_values(by='B', inplace = True)

#sort by B column...ascending by default
#in place is if you want to persist that change on your original dataframe
#there are several methods that also have the inplace parameter

A         B         C         D         E
2018-12-31 -0.182122 -0.894725  1.023244 -2.232250  1.313546
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521  0.747274
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.457958
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229

### Selection

In [96]:
df[['A','B']]

#how to slice your dataframe

A         B
2014-01-01 -0.715416  0.859711
2015-01-01  0.026003 -0.089616
2016-01-01 -0.020582 -0.587065
2016-12-31 -0.538891 -0.677628
2017-12-31  0.845594 -0.616776
2018-12-31 -0.182122 -0.894725

In [97]:
df[0:3]

#returns the first 2 rows.... row0, row1, row3

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425

In [98]:
print dates
df.loc[dates[0]]
# By label
#this is grabbing the row by an index
# df[df.index == pd.Timestamp('2014-01-01')]
#this does the same thing but returns in a dataframe table



DatetimeIndex(['2014-01-01', '2015-01-01', '2016-01-01', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='365D')


A   -0.715416
B    0.859711
C   -0.176055
D    0.070512
E   -0.781229
Name: 2014-01-01 00:00:00, dtype: float64

In [99]:
df[df.index == pd.Timestamp('2014-01-01')]


A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229

In [104]:
a = df.loc[:,['A','B']]
# multi-axis by label
#this is another way of slicing your dataframe


b = df.loc['2014-01-01':'2014-01-03', ['A','B']]
#give me rows from 2014-01-01 to 2014-01-03 and I only want columns A and B


c = df[['A','B']]['2014-01-01':'2014-01-03']


d = df [(df.index >= '2014-01-01') & (df.index <= '2014-01-03')][['A','B']]



print a
print b
print c
print d


                   A         B
2014-01-01 -0.715416  0.859711
2015-01-01  0.026003 -0.089616
2016-01-01 -0.020582 -0.587065
2016-12-31 -0.538891 -0.677628
2017-12-31  0.845594 -0.616776
2018-12-31 -0.182122 -0.894725
                   A         B
2014-01-01 -0.715416  0.859711
                   A         B
2014-01-01 -0.715416  0.859711
                   A         B
2014-01-01 -0.715416  0.859711


In [111]:
# Date Range
df.loc['20140101':'20150109',['B']]

B
2014-01-01  0.859711
2015-01-01 -0.089616

In [77]:
# Fast access to scalar
df.at[dates[1],'B']

0.081150581580162875

In [78]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D         E
2016-12-31  0.770334  0.333293  1.600785  1.055417 -1.065898
2017-12-31 -1.169524 -1.355800  0.337845 -0.568655 -1.688358
2018-12-31  0.163111 -1.186679 -0.479321 -1.089277 -0.370649

### Boolean Indexing

In [105]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521  0.747274
2018-12-31 -0.182122 -0.894725  1.023244 -2.232250  1.313546

### Setting

In [115]:
df_posA = df.copy() # Without "copy" it would act on the dataset
df_posA.head()

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521  0.747274
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.457958

In [116]:
df_posA[df_posA.A < 0] = -1*df_posA
df_posA.head()
#only has rows who set column is less than zero

A         B         C         D         E
2014-01-01  0.715416 -0.859711  0.176055 -0.070512  0.781229
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2016-01-01  0.020582  0.587065  1.613610  0.648030  0.824425
2016-12-31  0.538891  0.677628  1.321461  1.046521 -0.747274
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.457958

In [ ]:
df_posA

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes

### Applying functions

In [ ]:
#use apply when you want to derive a new column

In [117]:
df
df.head()

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512 -0.781229
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  0.650946
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -0.824425
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521  0.747274
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.457958

In [121]:
df['E'] = df.D.apply(lambda x: x*2)
df.head()

#create a new column called E, but refer to column D to derive column E
#df.D is a series
#take every value of D and multiply by 2

A         B         C         D         E
2014-01-01 -0.715416  0.859711 -0.176055  0.070512  0.141024
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  1.635598
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -1.296060
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521 -2.093043
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.362857

In [122]:
def multiplyBy2(val): return val*2
df['F'] = df.D.apply(multiplyBy2)
df.head()

A         B         C         D         E         F
2014-01-01 -0.715416  0.859711 -0.176055  0.070512  0.141024  0.141024
2015-01-01  0.026003 -0.089616 -0.025000  0.817799  1.635598  1.635598
2016-01-01 -0.020582 -0.587065 -1.613610 -0.648030 -1.296060 -1.296060
2016-12-31 -0.538891 -0.677628 -1.321461 -1.046521 -2.093043 -2.093043
2017-12-31  0.845594 -0.616776 -0.164049 -0.181428 -0.362857 -0.362857

In [129]:
a = df.apply(np.cumsum)
#applies cummulative sum from rows top-down
#row1 + row2

b= df.apply(np.cumsum, axis = 1)
#same operation done from column to column
#col1 + col2

print a.head()
print b.head()

                   A         B         C         D         E         F
2014-01-01 -0.715416  0.859711 -0.176055  0.070512  0.141024  0.141024
2015-01-01 -0.689413  0.770095 -0.201055  0.888311  1.776621  1.776621
2016-01-01 -0.709995  0.183031 -1.814665  0.240281  0.480561  0.480561
2016-12-31 -1.248886 -0.494597 -3.136126 -0.806241 -1.612481 -1.612481
2017-12-31 -0.403291 -1.111373 -3.300175 -0.987669 -1.975338 -1.975338
                   A         B         C         D         E         F
2014-01-01 -0.715416  0.144296 -0.031760  0.038752  0.179776  0.320800
2015-01-01  0.026003 -0.063613 -0.088613  0.729186  2.364784  4.000382
2016-01-01 -0.020582 -0.607647 -2.221257 -2.869287 -4.165347 -5.461407
2016-12-31 -0.538891 -1.216519 -2.537980 -3.584501 -5.677544 -7.770587
2017-12-31  0.845594  0.228819  0.064769 -0.116659 -0.479516 -0.842373


In [130]:
import math
df.apply(lambda x: x.max() - x.min()).head()

#axis doesn't matter here because the operation is being performed on every element


A    1.561010
B    1.754436
C    2.636854
D    3.050048
E    6.100097
dtype: float64

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Merge

In [ ]:
np.random.randn(10,4)

In [ ]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

In [ ]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas